---
spring:
  application:
    name: spring-cloud-eureka
  config:
    activate:
      on-profile: peer1
server:
  port: 8000
eureka:
  instance:
    hostname: peer1
  client:
    serviceUrl:
      defaultZone: http://152.136.110.205:8001/eureka/,http://152.136.110.205:8002/eureka/
---
spring:
  application:
    name: spring-cloud-eureka
  config:
    activate:
      on-profile: peer2
server:
  port: 8001
eureka:
  instance:
    hostname: peer2
  client:
    serviceUrl:
      defaultZone: http://152.136.110.205:8000/eureka/,http://152.136.110.205:8002/eureka/
---
spring:
  application:
    name: spring-cloud-eureka
  config:
    activate:
      on-profile: peer3
server:
  port: 8002
eureka:
  instance:
    hostname: peer3
  client:
    serviceUrl:
      defaultZone: http://152.136.110.205:8000/eureka/,http://152.136.110.205:8001/eureka/
